spring:
  application:
    name: USER-SERVICE

server:
  port: 9002

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

app:
  department:
    service:
      url: http://DEPARTMENT-SERVICE/department/?id=